blog1/urls.py
from django.urls import path
from django.shortcuts import render
from . import views

namespace="blog1"
####fk means foreign key
urlpatterns = [
    path('',views.home, name='home' ),
    path('<str:slug>',views.postdetail, name='postdetail' ),
    path('Category/<str:name>',views.postcategory, name='postcategory' ),
]

home/urls.py
from django.urls import path
from . import views

namespace = "home"
urlpatterns =[
    path('', views.homepage,name='home'),
    path('register', views.signup,name='register'),
    path('login', views.login,name='login'),
    path('logout', views.logout,name='logout'),
    path('search', views.search,name='search'),
    path('contact', views.contact,name='contact')

]

newblog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'),namespace='home')),
    path('blog/', include(('blog1.urls','blog'),namespace='blog1')),
    path('video/', include(('video.urls','video'),namespace='video')),
    path('products/', include(('products.urls','products'),namespace='products'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name=models.CharField(max_length=100)
    username=models.CharField(max_length=50)
    contactno=models.IntegerField()
    email=models.EmailField(max_length=100)
    msg=models.CharField(max_length=100)

    def __str__(self):
        return self.username + " " + self.msg[:10]

home/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate
from django.contrib.auth.models import User, auth
from django.contrib import messages
from blog1.models import Post
from home.models import Contact


# Create your views here.

def homepage(request):
    return render(request,'home/index.html')

def signup(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['pass']
        cpassword = request.POST['confpass']

        if firstname == "":
            messages.error(request,"First Name should not be empty")
            return redirect('/register')
        elif lastname == "":
            messages.error(request,"Last Name should not be empty")
            return redirect('/register')
        elif username == "":
            messages.error(request,"Username should not be empty")
            return redirect('/register')
        elif email == "":
            messages.error(request,"Email should not be empty")
            return redirect('/register')
        elif password == "":
            messages.error(request,"Password should not be empty")
            return redirect('/register')
        elif cpassword == "":
            messages.error(request,"Confim Password should not be empty")
            return redirect('/register')
        elif password == cpassword:
            messages.error(request,"Password and Confim Password should be same")
            return redirect('/register')
        elif len(username) > 7:
            messages.error(request,"Username should not be more than 7 characters")
            return redirect('/register') 
        else:
            if User.objects.filter(username=username).exists():
                messages.error(request,'Username not available')
                return redirect("/register")
            elif User.objects.filter(email=email).exists():
                messages.error(request,'Email already exists')
                return redirect("/register")
            else:
                user = User.objects.create_user(username=username,password=password,email=email,first_name=firstname,last_name=lastname)
                user.save()
                messages.info(request,'Registered Successfully')
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return redirect('/')
    else:
        return render(request,'home/register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            messages.info(request,'Login Successfully')
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')
        else:
            messages.error(request,'Check Username or Password')
            return redirect('/login')
    else:
        return render(request,'home/login.html')
        
def logout(request):
    auth.logout(request)
    return redirect('/')

def search(request):
    query = request.GET['query']
    if(len(query)>60):
        posts = Post.objects.none()
    else:
        posttitles = Post.objects.filter(title__icontains = query)
        postcontents = Post.objects.filter(desc__icontains = query)
        posts=posttitles.union(postcontents)

    if posts.count()==0:
        messages.warning(request,"No search result found")
    context = {'posts':posts,'query':query} 

    return render(request,'home/search.html',context)

def contact(request):
    if request.method=='POST':
        name=request.POST['name']
        username='dddd'
        email=request.POST['email']
        contact=request.POST['contact']
        msg=request.POST['msg']
        print(username)
        # if len(name)<2 or len(email)<3 or len(phone)<10 or len(content)<3 :
        #     messages.error(request,"Please fill the form corectly")
        # else:
        contact=Contact(name=name,username=username,email=email,contactno=contact,msg=msg)
        contact.save()
        messages.success(request,"Thank you for contacting us")
        return redirect("/contact")
    else:
        return render(request,'home/contact.html')
    
    return render(request,'home/conatct.html')

templates/home/contact.html
{% extends 'base.html' %}
{% block title %}Contact us{% endblock title %}
{% block contactactive %}active{% endblock contactactive %}
{% block content %}
<div class="container">
    <h1>Contact Us</h1>
    <form method="post" action="/contact">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" id="name" name="name" class="form-control" aria-describedby="name">
            </div>
        <div class="form-group">

          <label for="email">Email address</label>
          <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="phone">Phone Number</label>
          <input type="phone" class="form-control" id="phone" name="contact">
        </div>
        <div class="form-group">
          <label for="content">Describe your issue:</label>
          <textarea class="form-control" name="msg" id="content" cols="30" rows="6"></textarea>
        </div>
       
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
{% endblock content%}

templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
    <h3>Welcome to home page</h3>
    </div>
</div>
{% endblock content %}

templates/home/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <form method="POST" action="login">
            {% csrf_token %}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
              {% endif %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" name="username" id="username">
            </div>
            <div class="mb-3">
                <label for="pass" class="form-label">Password</label>
                <input type="password" class="form-control" name="password" id="pass">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/home/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <form action="register" method="POST">
            {% csrf_token %}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
              {% endif %}  
            <div class="mb-3">
                <label for="firstname" class="form-label">First Name</label>
                <input type="text" class="form-control" name="firstname" id="firstname">
            </div>
            <div class="mb-3">
                <label for="lastname" class="form-label">Last Name</label>
                <input type="text" class="form-control" name="lastname" id="lastname">
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" name="username" id="username">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" name="email" id="email">
            </div>
            <div class="mb-3">
                <label for="pass" class="form-label">Password</label>
                <input type="password" class="form-control" name="pass" id="pass">
            </div>
            <div class="mb-3">
                <label for="confpass" class="form-label">Confirm Password</label>
                <input type="password" class="form-control" name="confpass" id="confpass">
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>
<h3> Request Object attributes</h3>
<ul>
    <li>{{ request.scheme }}</li>
    <li>{{ request.method }}</li>
    <li>{{ request.path }}</li>
    <li>{{ request.GET }}</li>
    <li>{{ request.POST }}</li>
    <li>{{ request.user }}</li>

</ul>
{% endblock content %}

templates/home/search.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h2>Welcome to Search page</h2>
        <div class="col">    
            {% if posts|length < 1 %}
            <p>Your search query - <b>{{query}}</b> did not match any documents.</p>
            {% endif %}
            {% for p in posts %}
                <h2><a href="{% url 'blog:postdetail' p.slug %}">{{p.title}}</a></h2>
                <span>Author: {{p.author}}</span>
                <p>{{p.desc}}</p>  
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}