home/urls.py
from django.urls import path
from . import views

namespace = "home"
urlpatterns =[
    path('', views.homepage,name='home'),
    path('register', views.signup,name='register'),
    path('login', views.login,name='login'),
    path('logout', views.logout,name='logout'),
    path('search', views.search,name='search'),
    path('contact', views.contact,name='contact')

]

newblog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'),namespace='home')),
    path('blog/', include(('blog1.urls','blog'),namespace='blog1')),
    path('video/', include(('video.urls','video'),namespace='video')),
    path('products/', include(('products.urls','products'),namespace='products'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from django.shortcuts import render
from . import views

namespace="products"
urlpatterns = [
    path('',views.products, name='products' ),
    path('<str:slug>',views.catproducts, name='catproducts' ),
    path('<str:slug>/',views.productdetail, name='productdetail' ),
]

products/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(max_length=70)
    slug = models.SlugField(max_length=70,unique=True)
    img = models.ImageField(upload_to='prdctcatimages')

    def __str__(self):
        return self.name
    
    @property
    def image_url(self):
        if self.img and hasattr(self.img,'url'):
            return self.img.url

class Products(models.Model):
    product_id=models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    category = models.ForeignKey(ProductCategory,on_delete=models.CASCADE)
    desc = models.TextField()
    price=models.IntegerField()
    slug = models.SlugField(unique=True)
    img=models.ImageField(upload_to='productimages')
    timestamp = models.DateTimeField(blank=True)

    def __str__(self):
        return self.name[:15]
    
    @property
    def image_url(self):
        if self.img and hasattr(self.img,'url'):
            return self.img.url

products/views.py
from django.shortcuts import render
from products.models import ProductCategory, Products
# Create your views here.
def products(request):
    category = ProductCategory.objects.all()
    products = Products.objects.all()
    context = {'category':category,'products':products}
    return render(request,'products/index.html', context)

def catproducts(request,slug):
    print('catproduct')
    cat = ProductCategory.objects.filter(slug=slug).first()
    products = Products.objects.filter(category=cat)
    context = {'products':products}
    return render(request,'products/catproducts.html',context)

def productdetail(request,slug):
    print('productdetail')
    product = Products.objects.filter(slug=slug).first()
    context = {'product':product}
    return render(request,'products/productdetail.html',context)

templates/products/catproducts.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% for product in products %}
            <div class="col-md-6">
                <div class="productimg" width="100%" style="margin:auto;max-width:100%;text-align:center;max-height:350px;">
                    <img width="280" height="auto" style="max-height:350px;" src="{{product.img.url}}">
                </div>
                <div class="productinfo">
                    <a href="{% url 'products:productdetail' product.slug %}"><h5>{{product.name}}</h5></a>
                    <span style="font-weight:bold;">Price: {{product.price}}</span>
                    <br/>
                    <p>{{product.desc}}</p>
                </div>           
            </div>
        {% endfor %}        
    </div>
</div>
{% endblock content %} 

templates/products/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2" style="text-align:center;">
            <h5>Categories</h5>
            {% for c in category %}
                <div class="category-list" style="margin-top:20px;">
                    <a href="{% url 'products:catproducts' c.slug %}" style="text-decoration:none;"><h5 style="color:black;">{{c.name}}</h5></a>
                </div>
            {% endfor %}
        </div>
        <div class="col-md-10">
                {% for product in products %}
                    <div class="col-md-6">
                        <div class="productimg" width="100%" style="margin:auto;max-width:100%;text-align:center;max-height:350px;">
                            <img width="280" height="auto" style="max-height:350px;" src="{{product.img.url}}">
                        </div>
                        <div class="productinfo">
                            <a href="{% url 'products:productdetail' product.slug %}"><h5>{{product.name}}</h5></a>
                            <span style="font-weight:bold;">Price: {{product.price}}</span>
                            <br/>
                            <p>{{product.desc}}</p>
                        </div>           
                    </div>
                {% endfor %}
        </div>
    </div>
</div>
{% endblock content %} 

templates/products/productdetail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2>Product Detail</h2>
    <div class="row" id="{{product.product_id}}">
             <div class="col-md-4">
                 <img style="max-width:100%;" src="{{product.img.url}}">
             </div>
             <div class="col-md-8">
                 <h3>{{product.name}}</h3>
                 <strong><span>Price: {{product.price}}</span></strong>
                 <br/>
                 <p>{{product.desc}}</p>
                 <button>Add to Cart</button>
             </div>
    </div>
</div>
{% endblock content %}