home/urls.py
from django.urls import path
from . import views

namespace = "home"
urlpatterns =[
    path('', views.homepage,name='home'),
    path('register', views.signup,name='register'),
    path('login', views.login,name='login'),
    path('logout', views.logout,name='logout'),
    path('search', views.search,name='search'),
    path('contact', views.contact,name='contact')

]

newblog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'),namespace='home')),
    path('blog/', include(('blog1.urls','blog'),namespace='blog1')),
    path('video/', include(('video.urls','video'),namespace='video')),
    path('products/', include(('products.urls','products'),namespace='products'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from django.shortcuts import render
from . import views

namespace="video"
####fk means foreign key

urlpatterns = [
    path('',views.categorylist, name='catlist' ),
    path('videocomment',views.videocomment, name='videocomment' ),
    path('<slug:slug>',views.videodetail, name='videodetail' ),
    path('<slug:slug>/',views.categoryvideos, name='catvideo' ),
    
    
]

video/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from embed_video.fields import EmbedVideoField
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=30)
    img=models.ImageField(upload_to='videocatpics', blank=True)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.name

class Item(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(unique=True)
    img=models.ImageField(upload_to='videothumbnail')
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    video=EmbedVideoField()
    desc=models.TextField()
    publish=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class VideoComment(models.Model):
    comment=models.TextField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    video=models.ForeignKey(Item,on_delete=models.CASCADE)
    parent=models.ForeignKey('self',on_delete=models.CASCADE,null=True)
    timestamp=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment[:15] + "....." + "by" + self.user.username

video/views.py
from django.core.checks import messages
from django.db.models.query_utils import PathInfo
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from video.models import Category, Item, VideoComment
from django.contrib import messages
from django.urls import reverse

# Create your views here.
def categorylist(request):
    categories = Category.objects.all()
    context={'categories':categories}
    return render(request, 'video/categorylist.html',context)

def categoryvideos(request,slug):
    print('category')
    category=Category.objects.filter(slug=slug).first()
    catvideos = Item.objects.filter(category=category)
    context={'catvideos':catvideos}
    return render(request,'video/catvideo.html',context)

def videodetail(request,slug):
    video=Item.objects.filter(slug=slug).first()
    comments=VideoComment.objects.filter(video=video,parent=None)
    replies=VideoComment.objects.filter(video=video).exclude(parent=None)
    repDict={}
    for reply in replies:
        print(reply.comment)
        if reply.parent.id not in repDict.keys():
            repDict[reply.parent.id]=[reply]
        else:
            repDict[reply.parent.id].append(reply)

        print(reply)
        print(reply.parent.id)
    context = {'videos':video,'comments':comments,'user':request.user,'repDict':repDict}
    
    return render(request,'video/videodetail.html',context)

def videocomment(request):
    if request.method == 'POST':
        videocomment=request.POST['comment']
        user=request.user
        videosno=request.POST['videoSno']
        video=Item.objects.get(id=videosno)
        print(video)
        parentsno=request.POST['parentSno']
        if parentsno=="":
            comment1=VideoComment(comment=videocomment,user=user,video=video)      
            comment1.save()
            messages.success(request,"Your Comment has been posted successfully")
            return HttpResponseRedirect(reverse('video:videodetail',args=(video.slug,)))
        else:
            print('parent')
            parent=VideoComment.objects.get(id=parentsno)
            comment1=VideoComment(comment=videocomment,user=user,video=video,parent=parent) 
            comment1.save()
            messages.success(request,"Your reply has been added")
            return HttpResponseRedirect(reverse('video:videodetail',args=(video.slug,)))

templates/video/categorylist.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2>Video Categories</h2>
    <div class="row">
    {% for c in categories %}
            <div class="col-md-6">
                <h5><a href="{% url 'video:catvideo' c.slug %}">{{ c.name }}</a></h5>
                <img style="height:120px;width:150px" src="{{c.img.url}}">
            </div>
    {% endfor %}
    </div>
</div>
{% endblock content %} 

templates/video/catvideo.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
    {% for video in catvideos %}
        <div class="col-md-4">
            <h3>{{video.title}}</h3>
            <img style="height:120px;width:150px" src="{{video.img.url}}">
            <a href="{% url 'video:videodetail' video.slug %}">Click to open video</a>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

templates/video/videodetail.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% load static %} 
{% load extras %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>{{videos.title}}</h2>
            <div class="container embed-responsive embed-responsive-16by9 px-3" id="vid">
             {% video videos.video 'small' %}
            </div>
        </div>
    </div>
    <div class="row">
        {% if user.is_authenticated %}
            <div>
                <form method="POST" action="/video/videocomment">
                {% csrf_token %}
                Post a Comment:<input type="text" name="comment">
                <input type="hidden" name="parentSno" value="">
                <input type="hidden" name="videoSno" value="{{ videos.id }}">
                <input type="submit" value="Post">
                </fom>
            </div>
        {% else %}
        <div class="col">
            <h2><a href="/login?next={% firstof request.path '/'%}">Login</a> or <a href="{% url 'home:register' %}?next={% firstof request.path '/' %}">Register</a>  to Comment</h2>
        </div>
        {% endif %}
    </div>
    <div class="row">
    <h3>{{comments.count}} {% if comments.count == 0 %} No Comment {% elif comments.count == 1 %} Comment {% else %} Comments {% endif %}</h3>
    {% for comment in comments %}
        <div class="col">
            <div class="col-md-2">
                <img style="width:100px" src="{% static 'images/user.jpg' %}">
            </div>
            <div class="col-md-10">
                <p><strong>{{comment.user}}</strong> <span>{{comment.timestamp}}</span></p>
                <p>{{ comment.comment}}</p>
                <div class="reply mx-0">
                    {% if user.is_authenticated %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.id}}" aria-expanded="false" aria-controls="replyBox{{comment.id}}">
                        Reply
                    </button>
                    <div class="collapse" id="replyBox{{comment.id}}">
                        <div class="card card-body my-2">
                            <form method="POST" action="/video/videocomment">
                            {% csrf_token %}
                                Post a Reply:<input type="text" name="comment">
                                <input type="hidden" name="parentSno" value="{{comment.id}}">
                                <input type="hidden" name="videoSno" value="{{ videos.id }}">
                                <input type="submit" value="Post">
                            </fom>
                        </div>
                    </div>
                    {% else %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.id}}" aria-expanded="false" aria-controls="replyBox{{comment.id}}" disabled>
                       Reply
                    </button>
                    {% endif %}
                    <div class="replies my-2">
                        {% comment %} {% for reply in repDict|get_val:comment.id %} {% endcomment %}
                        {% for reply in repDict|get_val:comment.id %}
                        <div class="row">
                            <div class="col-md-2">
                                <img class="rounded  -auto d-block" src="{% static 'images/user.jpg' %}" alt="" style="width: 67px;"> 
                            </div>
                            <div class="col-md-10">
                                <b>{{reply.user.username}}</b> &nbsp; <span class="badge badge-secondary" style="font-size: 13px;">{{reply.timestamp}}</span>
                                <div>{{ reply.comment }}</div>

                        </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content%}