home/urls.py
from django.urls import path
from . import views

namespace = "home"
urlpatterns =[
    path('', views.homepage,name='home'),
    path('register', views.signup,name='register'),
    path('login', views.login,name='login'),
    path('logout', views.logout,name='logout'),
    path('search', views.search,name='search'),
    path('contact', views.contact,name='contact')

]

newblog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'),namespace='home')),
    path('blog/', include(('blog1.urls','blog'),namespace='blog1')),
    path('video/', include(('video.urls','video'),namespace='video')),
    path('products/', include(('products.urls','products'),namespace='products'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-5.1.2-dist\css\bootstrap.min.css' %}">
    {% block mycss %} {% endblock mycss %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">MySite</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="\blog">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="\products">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="\video">Videos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/contact">Contact Us</a>
              </li>
              {% comment %} <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> {% endcomment %}
              {% comment %} <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li> {% endcomment %}
            </ul>
            <form class="d-flex" action="/search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <ul class="navbar-nav mb-2 mb-lg-0">
              {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="">Hi {{ user.first_name}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:login' %}">Login</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          <strong>New Message: {{ message }}</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
      {% block content %}
      {% endblock content %}
      <script src="{% static 'bootstrap-5.1.2-dist\js\bootstrap.bundle.min.js' %}"></script>
</body>
</html>